[project]
directory = "."
sources = ["axis_adapter.v"]
toplevel = "axis_adapter"

[[bugs]]
name = "s3"
original = "axis_adapter.v"
buggy = "axis_adapter_bug_s3.v"

[[testbenches]]
name = "csv"
table = "tb.csv"

# original Verilog testbench (ASPLOS'22)
[[testbenches]]
name = "verilog"
tags = ["original"]
sources = ["tb.v"]
output = "output.txt"
oracle = "tb.csv"