[package]
name = "synth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap =  { version = "4.4.11", features = ["derive"] }
libpatron = "0.3.1"
memmap2 = "0.9.0"
serde_json = "1.0.108"
