[package]
name = "synth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap =  { version = "4.5", features = ["derive"] }
patronus = "0.32.0"
memmap2 = "0.9.5"
num-bigint = "0.4.6"
num-traits = "0.2.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }

[profile.release]
debug = 1
